remote_theme: "mmistakes/minimal-mistakes@4.24.0"
title: Aleksandr Vinokurov
description: Memos
show_downloads: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "aleksandrvin"
plugins:
  - jekyll-include-cache

