theme: jekyll-theme-hacker
title: Aleksandr Vinokurov
description: Memos
show_downloads: false
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      author: "aleksandrvin"
