version: "3.8"

services:
  jekyll:
    image: ruby:2
    command: |
      sh -c 'bundle install && exec jekyll serve --host 0.0.0.0 --drafts'
    working_dir: /code
    volumes:
      - .:/code
      - gems:/usr/local/bundle/gems
    ports:
      - "4000:4000"

volumes:
  gems:
