#+TITLE: aleksandr.vin
#+AUTHOR: Aleksandr Vinokurov
#+DATE: 2020-10-15

* Sometimes you're forced to use old tools [2020-10-15]

  Somebody's playing in security. You need to use *docker-machine*
  because you can't run native *docker* on localhost /(last [[https://github.com/docker/machine/commit/b170508bf44c3405e079e26d5fdffe35a64c6972][commit]] to
  docker-machine repo on github was made more than a year ago)/. And
  it doesn't work from the box.  So you're tuning it up /(like almost
  everything on Linux)/.

  This time the problem was in names' differences of default shared
  folder (host ~/home~ was mounted as ~/hosthome~ in guest vm, where
  actual docker engine runs), and rather loosy behaviour of ~-v~,
  ~--volume~ option of ~docker run~ in comparison to more explicit
  ~--mount~. See question answer on [[https://superuser.com/a/1594651/1230369][superuser.com]].

* Something to start with [2020-10-15]

  #+BEGIN_QUOTE
  Everything should be made as simple as possible,
  but not any simpler ---Albert Einstein
  #+END_QUOTE

** I made it. Again. After, maybe, 10 years.

   And again I have the same mood here, I think. I'm home alone, listening to
   blues.

** Here is a link to a note I made last evening about
   [[https://superuser.com/a/1594385/1230369][resizing ext4 partition of a guest Ubuntu on vmdk on ESXi 6.0]].

   I spent some time finding out how to atually resize the disk and wrote down
   the steps to remember, and now I have mine *aleksandr.vin*
   domain name and a site running on github pages.

** Thoughts about VR (home) office
   
   Last Friday my colleague told me about Oculus Quest 2. Checking the specs,
   I had the same feeling when was reading about DJI Mavic Air 2... after not
   following any updates on DJI for a 2 years. As the VR headset become much
   more powerful and much less heavy, I returned to old idea of using VR headset
   as a replacement for home office monitor(s) for coding. It should be ok to
   have 2K per eye on resolution, but the questions are:

     + Will it be warm to work?

     + Will it be ok to work for 1 hour before the break (also maintaining
       regular breaks should become a habbit)?

     + Eyes strain and degradation?

   So I'm thiking about giving it a try in upcoming months.
   
   
